# Generated by Django 5.0.4 on 2026-08-12 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orientacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Orientación',
                'verbose_name_plural': 'Orientaciones',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('codigo_iso', models.CharField(help_text='Ej: PE, UY, CL', max_length=2, verbose_name='Código ISO')),
                ('bandera_emoji', models.CharField(help_text='Ej: 🇵🇪 (temporal, reemplazar por ícono de bandera real)', max_length=8)),
                ('moneda', models.CharField(help_text='Código ISO de moneda, ej: PEN, UYU', max_length=3, verbose_name='Moneda')),
                ('activo', models.BooleanField(default=False, help_text='Recién se activa cuando el país está listo para mostrarse al público')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Publico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Público',
                'verbose_name_plural': 'Públicos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('matricula', models.CharField(max_length=60, verbose_name='Matrícula profesional')),
                ('whatsapp', models.CharField(max_length=30)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('modalidad', models.CharField(choices=[('online', 'Online'), ('presencial', 'Presencial'), ('ambas', 'Online y presencial')], default='online', max_length=12)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='psicologos/')),
                ('bio', models.TextField(blank=True)),
                ('suscripcion_activa', models.BooleanField(default=False)),
                ('dlocal_subscription_id', models.CharField(blank=True, max_length=100)),
                ('exento_de_pago', models.BooleanField(default=False, verbose_name='Exenta de pago (fundadora)')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('orientaciones', models.ManyToManyField(blank=True, related_name='psicologos', to='directorio.orientacion')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='psicologos', to='directorio.pais')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psicologo', to=settings.AUTH_USER_MODEL)),
                ('publicos', models.ManyToManyField(blank=True, related_name='psicologos', to='directorio.publico')),
            ],
            options={
                'verbose_name': 'Psicólogo',
                'verbose_name_plural': 'Psicólogos',
                'ordering': ['nombre'],
            },
        ),
    ]
