# Generated by Django 5.0.4 on 2026-08-12 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='etiqueta_matricula',
            field=models.CharField(default='N° de Matrícula', help_text='Ej: "N° de Colegiatura", "N° de Matrícula", "N° de Cédula Profesional"', max_length=60, verbose_name='Etiqueta de habilitación profesional'),
        ),
        migrations.AddField(
            model_name='pais',
            name='muestra_precio_sesion',
            field=models.BooleanField(default=False, help_text='Convención de mercado: en Perú se acostumbra publicar el costo de la sesión en el perfil, en otros países no', verbose_name='Mostrar precio de sesión en el perfil'),
        ),
        migrations.AddField(
            model_name='pais',
            name='simbolo_moneda',
            field=models.CharField(blank=True, help_text='Ej: S/, $U, $', max_length=6, verbose_name='Símbolo de moneda'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='docencia',
            field=models.TextField(blank=True, help_text='Un párrafo con la experiencia dando clases/formación a otros, si tiene', verbose_name='Docencia'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='fecha_pago_confirmado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='precio_sesion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Solo se muestra en el perfil público si el país lo tiene habilitado (ver Pais.muestra_precio_sesion)', max_digits=8, null=True, verbose_name='Precio de sesión'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='publicado_por_usuario',
            field=models.BooleanField(default=False, verbose_name='Publicado por el profesional'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='recordatorio_pago_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='recordatorio_perfil_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='matricula',
            field=models.CharField(max_length=60, verbose_name='N° de habilitación profesional'),
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: "Licenciada en Psicología. Universidad X"', max_length=300)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formaciones', to='directorio.psicologo')),
            ],
            options={
                'verbose_name': 'Formación',
                'verbose_name_plural': 'Formaciones',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
