# Generated by Django 6.1 on 2026-08-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0002_pais_etiqueta_matricula_pais_muestra_precio_sesion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='bandera_emoji',
            field=models.CharField(help_text='Ej: 🇵🇪 -- ya no se usa para mostrar la bandera en el sitio (eso sale de bandera_svg), se mantiene solo de referencia', max_length=8),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='precio_sesion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Se muestra en tu perfil público.', max_digits=8, null=True, verbose_name='Precio de sesión'),
        ),
    ]
