# Generated by Django 6.1 on 2026-08-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0003_alter_pais_bandera_emoji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='es_externo',
            field=models.BooleanField(default=False, help_text='Marcar para Argentina: la bandera linkea directo a url_externa en vez de abrir el buscador de acá', verbose_name='Es un sitio externo (no vive en este proyecto)'),
        ),
        migrations.AddField(
            model_name='pais',
            name='url_externa',
            field=models.URLField(blank=True, help_text='Solo si "Es un sitio externo" está tildado, ej: https://atencionpsi.com.ar', verbose_name='URL externa'),
        ),
    ]
