# Generated by Django 6.1 on 2026-08-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0004_pais_es_externo_pais_url_externa'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='sesiones_atendidas',
            field=models.PositiveIntegerField(blank=True, choices=[(100, 'Más de 100'), (500, 'Más de 500'), (1000, 'Más de 1.000'), (2000, 'Más de 2.000')], help_text='Elegí el rango que mejor represente tu trayectoria profesional (no hace falta ser exacto).', null=True, verbose_name='Sesiones atendidas (aprox.)'),
        ),
    ]
