# Generated by Django 6.0.4 on 2026-09-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0006_seed_paises'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='precio_basico',
            field=models.PositiveIntegerField(default=0, help_text='En la moneda de este país, sin decimales. Ej: 49 (soles), 590 (pesos uruguayos)', verbose_name='Precio Plan Básico (moneda local)'),
        ),
        migrations.AddField(
            model_name='pais',
            name='precio_premium',
            field=models.PositiveIntegerField(default=0, help_text='Básico + agenda de turnos online + difusión en el Instagram de Atención Psi del país', verbose_name='Precio Plan Premium (moneda local)'),
        ),
    ]
