# Generated by Django 6.0.4 on 2026-09-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0008_seed_precios_planes'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Destacado en el home'),
        ),
    ]
