# Generated by Django 5.0.4 on 2026-09-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0009_psicologo_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='plan',
            field=models.CharField(choices=[('basico', 'Básico'), ('premium', 'Premium')], default='basico', max_length=10, verbose_name='Plan contratado'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='terminos_aceptados_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Términos aceptados el'),
        ),
    ]
