# Generated by Django 5.0.4 on 2026-10-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0011_desactivar_argentina_externa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='codigo_telefono',
            field=models.CharField(blank=True, help_text='Sin "+", ej: 51, 598, 56', max_length=4, verbose_name='Código telefónico de país'),
        ),
    ]
