# Generated by Django 6.0.4 on 2026-10-03 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0013_seed_codigos_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientacion',
            name='aprobado',
            field=models.BooleanField(default=True, help_text='Si está en False, lo propuso un profesional y solo lo ve él hasta que lo apruebes'),
        ),
        migrations.AddField(
            model_name='orientacion',
            name='propuesto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directorio.psicologo', verbose_name='Propuesto por'),
        ),
        migrations.AddField(
            model_name='publico',
            name='aprobado',
            field=models.BooleanField(default=True, help_text='Si está en False, lo propuso un profesional y solo lo ve él hasta que lo apruebes'),
        ),
        migrations.AddField(
            model_name='publico',
            name='propuesto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directorio.psicologo', verbose_name='Propuesto por'),
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('aprobado', models.BooleanField(default=True, help_text='Si está en False, la propuso un profesional y solo la ve él hasta que la apruebes')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='directorio.pais')),
                ('propuesto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directorio.psicologo', verbose_name='Propuesta por')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['pais', 'orden', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('pais', 'nombre'), name='ciudad_unica_por_pais')],
            },
        ),
    ]
