# Generated by Django 6.0.4 on 2026-10-03 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0015_seed_taxonomia_y_ciudades'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='pago_declinado_desde',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlanDLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basico', 'Básico'), ('premium', 'Premium')], max_length=10)),
                ('dlocal_plan_id', models.PositiveIntegerField(verbose_name='ID del plan en dLocal Go')),
                ('plan_token', models.CharField(max_length=100)),
                ('subscribe_url', models.URLField(max_length=300)),
                ('monto', models.PositiveIntegerField(help_text='Monto mensual con el que se creó, en moneda local')),
                ('moneda', models.CharField(max_length=3)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_dlocal', to='directorio.pais')),
            ],
            options={
                'verbose_name': 'Plan en dLocal Go',
                'verbose_name_plural': 'Planes en dLocal Go',
                'constraints': [models.UniqueConstraint(fields=('pais', 'plan'), name='plan_dlocal_unico_por_pais')],
            },
        ),
    ]
