# Generated by Django 6.0.4 on 2026-10-09 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0016_planes_dlocal_y_pago_declinado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('aprobado', models.BooleanField(default=True, help_text='Si está en False, la propuso un profesional y solo la ve él hasta que la apruebes')),
                ('propuesto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directorio.psicologo', verbose_name='Propuesta por')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='psicologo',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='psicologos', to='directorio.especialidad'),
        ),
    ]
