# Generated by Django 6.0.4 on 2026-10-09 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0018_seed_especialidades_y_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='gratis_hasta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gratis hasta'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='recordatorio_vencimiento_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CodigoFundador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Vacío = se genera uno solo', max_length=30, unique=True)),
                ('meses_gratis', models.PositiveSmallIntegerField(default=3)),
                ('usos_maximos', models.PositiveSmallIntegerField(default=1)),
                ('canjeable_hasta', models.DateField(blank=True, help_text='Último día para registrarse con este código (vacío = sin límite)', null=True)),
                ('nota', models.CharField(blank=True, help_text='Para quién es (ej: nombre del profesional)', max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pais', models.ForeignKey(blank=True, help_text='Vacío = vale en cualquier país', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos_fundador', to='directorio.pais')),
            ],
            options={
                'verbose_name': 'Código de fundador',
                'verbose_name_plural': 'Códigos de fundador',
                'ordering': ['-creado_en', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='psicologo',
            name='codigo_fundador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psicologos', to='directorio.codigofundador', verbose_name='Código de fundador usado'),
        ),
    ]
