# Generated by Django 6.1 on 2026-08-12 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directorio', '0002_pais_etiqueta_matricula_pais_muestra_precio_sesion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaNoAtiende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField(verbose_name='Desde')),
                ('fecha_hasta', models.DateField(verbose_name='Hasta')),
                ('motivo', models.CharField(blank=True, max_length=100)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_no_atiende', to='directorio.psicologo')),
            ],
            options={
                'verbose_name': 'Día que no atiende',
                'verbose_name_plural': 'Días que no atiende',
                'ordering': ['fecha_desde'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado')], verbose_name='Día de la semana')),
                ('hora_desde', models.TimeField(verbose_name='Desde')),
                ('hora_hasta', models.TimeField(verbose_name='Hasta')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad_semanal', to='directorio.psicologo')),
            ],
            options={
                'verbose_name': 'Bloque de disponibilidad semanal',
                'verbose_name_plural': 'Disponibilidad semanal',
                'ordering': ['dia_semana', 'hora_desde'],
            },
        ),
        migrations.CreateModel(
            name='TipoSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Individual, Pareja, Familiar', max_length=60)),
                ('duracion_min', models.PositiveIntegerField(default=50, verbose_name='Duración (minutos)')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_sesion', to='directorio.psicologo')),
            ],
            options={
                'verbose_name': 'Tipo de sesión',
                'verbose_name_plural': 'Tipos de sesión',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('modalidad', models.CharField(choices=[('online', 'Online'), ('presencial', 'Presencial')], max_length=12)),
                ('estado', models.CharField(choices=[('agendado', 'Agendado'), ('cancelado', 'Cancelado')], default='agendado', max_length=12)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('motivo_consulta', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='directorio.psicologo')),
                ('tipo_sesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='turnos.tiposesion')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
