# Generated by Django 5.0.4 on 2026-09-03 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0005_psicologo_sesiones_atendidas'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='notas_profesional',
            field=models.TextField(blank=True, help_text='Privadas, para esta sesión puntual.', verbose_name='Notas del profesional'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('realizado', 'Realizado'), ('ausente', 'No asistió'), ('cancelado', 'Cancelado')], default='agendado', max_length=12),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, help_text='Solo las ves vos. No se muestran en ningún lado público.', verbose_name='Notas privadas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='directorio.psicologo')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.AddField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='turnos.paciente'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('psicologo', 'email'), name='paciente_email_unico_por_psicologo'),
        ),
    ]
